[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/standalone.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/standalone.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
